export const roundToDecimals = (value, decimals = 2) => {
  const num = Number(value) || 0;
  return Math.round(num * Math.pow(10, decimals)) / Math.pow(10, decimals);
};

export const formatIndianNumber = (value, decimals = 2) => {
  const num = roundToDecimals(value, decimals);
  const [integer, decimal] = num.toFixed(decimals).split(".");

  let lastThree = integer.slice(-3);
  let remaining = integer.slice(0, -3);

  if (remaining) {
    lastThree = "," + lastThree;
  }

  const formatted = remaining.replace(/\B(?=(\d{2})+(?!\d))/g, ",") + lastThree;

  return decimals > 0 ? `${formatted}.${decimal}` : formatted;
};

export const formatCurrency = (value, decimals = 2) => {
  return `₹${formatIndianNumber(value, decimals)}`;
};

export const formatQuantity = (quantity, unit) => {
  const countableUnits = ["nos", "set", "pair", "bundle", "unit"];
  const normalizedUnit = (unit || "").toLowerCase().trim();

  if (countableUnits.includes(normalizedUnit)) {
    return Math.max(0, Math.round(Number(quantity) || 0));
  }

  return roundToDecimals(quantity, 2);
};

export const calculatePercentageChange = (oldValue, newValue) => {
  if (!oldValue || oldValue === 0) return "N/A";

  const change = ((newValue - oldValue) / oldValue) * 100;
  const sign = change >= 0 ? "+" : "";
  return `${sign}${roundToDecimals(change, 1)}%`;
};

export const formatPriceWithMetadata = (
  unitPrice,
  source,
  itemId = null,
  year = "2024"
) => {
  return {
    unitPrice: roundToDecimals(unitPrice, 2),
    source: source || "UNKNOWN",
    itemId: itemId,
    year: year,
    displayText: itemId
      ? `${source} ${year} Item No ${itemId} – ₹${formatIndianNumber(
          unitPrice,
          2
        )}`
      : `${source} ${year} – ₹${formatIndianNumber(unitPrice, 2)}`,
  };
};

export const addErrorMargin = (value, marginPercent = 5) => {
  const margin = (value * marginPercent) / 100;
  return {
    base: roundToDecimals(value, 2),
    min: roundToDecimals(value - margin, 2),
    max: roundToDecimals(value + margin, 2),
    margin: marginPercent,
    displayText: `₹${formatIndianNumber(value, 2)} (±${marginPercent}%)`,
  };
};

export const detectOutlier = (value, dataset, threshold = 90) => {
  const total = dataset.reduce((sum, val) => sum + val, 0);
  const percentage = (value / total) * 100;

  return {
    isOutlier: percentage > threshold,
    percentage: roundToDecimals(percentage, 1),
    warningText:
      percentage > threshold
        ? `Large-scale item (${roundToDecimals(
            percentage,
            1
          )}% of total); verify details.`
        : null,
  };
};

export const truncateText = (text, maxLength = 60) => {
  if (!text || text.length <= maxLength) return text;
  return text.substring(0, maxLength) + "...";
};

export const generateVersionFooter = (
  version = "1.0.0",
  sorVersion = "CPWD SOR 2024"
) => {
  const date = new Date().toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
  return `Generated by Road Safety Estimator Tool v${version} | ${sorVersion} | ${date} | For NRSH 2025`;
};

export default {
  roundToDecimals,
  formatIndianNumber,
  formatCurrency,
  formatQuantity,
  calculatePercentageChange,
  formatPriceWithMetadata,
  addErrorMargin,
  detectOutlier,
  truncateText,
  generateVersionFooter,
};
