export const roundToDecimals = (value, decimals = 2) => {
  const num = Number(value) || 0;
  return Math.round(num * Math.pow(10, decimals)) / Math.pow(10, decimals);
};

export const formatIndianNumber = (value, decimals = 2) => {
  const num = roundToDecimals(value, decimals);
  const parts = num.toFixed(decimals).split(".");
  const integer = parts[0];
  const decimal = parts[1];

  let lastThree = integer.slice(-3);
  let remaining = integer.slice(0, -3);

  if (remaining) {
    lastThree = "," + lastThree;
  }

  const formatted = remaining.replace(/\B(?=(\d{2})+(?!\d))/g, ",") + lastThree;

  return decimals > 0 ? `${formatted}.${decimal}` : formatted;
};

export const formatCurrency = (value, decimals = 2) => {
  return `₹${formatIndianNumber(value, decimals)}`;
};

export const truncateText = (text, maxLength = 60) => {
  if (!text || text.length <= maxLength) return text;
  return text.substring(0, maxLength) + "...";
};

export const generateVersionFooter = (
  version = "1.0.0",
  sorVersion = "CPWD SOR 2024"
) => {
  const date = new Date().toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
  return `Generated by Road Safety Estimator Tool v${version} | ${sorVersion} | ${date} | For NRSH 2025`;
};

export const getCategoryInfo = (categoryId, categoryName) => {
  const categoryMap = {
    A: {
      emoji: "🚸",
      tooltip: "Road Signs - Regulatory, warning, and informatory signs",
    },
    B: {
      emoji: "🛣️",
      tooltip: "Road Markings - Pavement markings and delineation",
    },
    C: {
      emoji: "🛡️",
      tooltip: "Safety Barriers - Crash barriers and guard rails",
    },
    D: {
      emoji: "💡",
      tooltip: "Lighting & Signals - Street lights and traffic signals",
    },
    E: {
      emoji: "⚠️",
      tooltip: "Traffic Control Devices - Cones, blinkers, delineators",
    },
    F: {
      emoji: "🏗️",
      tooltip: "Facilities & Infrastructure - Other road safety facilities",
    },
  };

  const info = categoryMap[categoryId] || {
    emoji: "📋",
    tooltip: categoryName,
  };
  return {
    ...info,
    id: categoryId,
    name: categoryName,
  };
};

export const formatSourceWithMetadata = (
  source,
  itemId = null,
  year = "2024"
) => {
  if (!source) return "N/A";

  if (itemId && source === "CPWD_SOR") {
    return `CPWD SOR ${year} Item No ${itemId}`;
  }

  if (itemId) {
    return `${source} ${year} (${itemId})`;
  }

  return `${source} ${year}`;
};

export const formatErrorMargin = (value, marginPercent = 5) => {
  const margin = (value * marginPercent) / 100;
  const min = roundToDecimals(value - margin, 2);
  const max = roundToDecimals(value + margin, 2);
  return `${formatCurrency(value)} (±${marginPercent}%: ${formatCurrency(
    min
  )} - ${formatCurrency(max)})`;
};

export const detectOutlierWarning = (value, total, threshold = 90) => {
  const percentage = (value / total) * 100;

  if (percentage > threshold) {
    return {
      isOutlier: true,
      percentage: roundToDecimals(percentage, 1),
      message: `⚠️ Large-scale item (${roundToDecimals(
        percentage,
        1
      )}% of total); verify spacing and count.`,
      severity: "warning",
    };
  }

  return null;
};

export const getConfidenceIndicator = (confidence) => {
  const indicators = {
    high: { color: "#10b981", text: "High", emoji: "✅", badge: "🟢" },
    medium: { color: "#f59e0b", text: "Medium", emoji: "⚠️", badge: "🟡" },
    low: { color: "#ef4444", text: "Low", emoji: "❌", badge: "🔴" },
    very_low: { color: "#991b1b", text: "Very Low", emoji: "⛔", badge: "🔴" },
  };

  return indicators[confidence] || indicators.medium;
};

export const getSourceBadge = (source) => {
  const sourceBadges = {
    CPWD_SOR: { badge: "🟢", label: "Verified SOR", color: "#10b981" },
    GeM: { badge: "🟢", label: "Verified GeM", color: "#10b981" },
    CATEGORY_FALLBACK: {
      badge: "🟡",
      label: "Fallback Rate",
      color: "#f59e0b",
    },
    DEFAULT: { badge: "🔴", label: "Assumed", color: "#ef4444" },
  };

  return sourceBadges[source] || sourceBadges.DEFAULT;
};

export const formatQuantityWithUnit = (quantity, unit) => {
  const rounded = roundToDecimals(quantity, 2);
  return `${rounded} ${unit}`;
};

export const createIRCLink = (ircReference) => {
  if (!ircReference) return null;

  const match = ircReference.match(
    /IRC(?::SP)?:(\d+)-(\d{4})\s*(?:Cl\.?\s*(.+))?/i
  );

  if (match) {
    const [, code, year, clause] = match;
    return {
      code: `IRC:${code}-${year}`,
      clause: clause ? `Cl. ${clause}` : null,
      url: `https://irc.gov.in/documents/irc-${code}-${year}/`,
      text: ircReference,
    };
  }

  return { text: ircReference, url: "https://irc.gov.in/" };
};

export default {
  roundToDecimals,
  formatIndianNumber,
  formatCurrency,
  truncateText,
  generateVersionFooter,
  getCategoryInfo,
  formatSourceWithMetadata,
  formatErrorMargin,
  detectOutlierWarning,
  getConfidenceIndicator,
  getSourceBadge,
  formatQuantityWithUnit,
  createIRCLink,
};
